# Generated by Django 2.1.4 on 2019-10-02 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AuthManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NickName', models.CharField(max_length=15, unique=True)),
                ('RealName', models.CharField(blank=True, max_length=10)),
                ('UserInf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserInf',
            },
        ),
    ]
