# Generated by Django 3.0.4 on 2021-03-29 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodsOwner', models.CharField(max_length=10)),
                ('GoodsName', models.CharField(max_length=30)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('ContactMethod', models.CharField(max_length=20)),
                ('BuyPrice', models.IntegerField()),
                ('SellPrice', models.IntegerField()),
                ('FirstImageName', models.CharField(max_length=10)),
                ('SecondImageName', models.CharField(max_length=10)),
                ('ThirdImageName', models.CharField(max_length=10)),
                ('GoodsKind', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.GoodsType')),
            ],
        ),
    ]
