# Generated by Django 2.1.4 on 2019-10-03 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('context', models.TextField()),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('ChangeTime', models.DateTimeField(auto_now=True)),
                ('LookTime', models.IntegerField(default=0)),
                ('CommentTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='articletype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.ArticleType'),
        ),
        migrations.AddField(
            model_name='article',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
