# Generated by Django 2.1.4 on 2019-10-05 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191004_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentUser', models.CharField(max_length=20)),
                ('context', models.TextField()),
                ('CommentTime', models.DateTimeField(auto_now_add=True)),
                ('CommentedArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.CreateModel(
            name='SecnodComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentUser', models.CharField(max_length=20)),
                ('context', models.TextField()),
                ('CommentTime', models.DateTimeField(auto_now_add=True)),
                ('SecnodCommentContext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleComment')),
            ],
        ),
    ]
